// Generated by scripts/fetch-publications.mjs — do not edit manually.
// Run `node scripts/fetch-publications.mjs` to regenerate from ORCID.

export interface Publication {
  title: string;
  authors: string;
  venue: string;
  year: string;
  doi?: string;
}

export const journalPapers: Publication[] = [
  {
    "title": "Addressing class collision and representation collapse in contrastive clustering via pseudo-supervised triplet and InfoNCE losses",
    "authors": "Kumar, A., Lee, D.-G.",
    "venue": "Applied Soft Computing",
    "year": "2026",
    "doi": "10.1016/j.asoc.2026.115751"
  },
  {
    "title": "An Efficient Method for Solving the Traveling Salesman Problem Using Modern Optimization Algorithms",
    "authors": "Nguyen Tram, Vaclav Snasel, Abhishek Kumar, Swagatam Das, van Du Nguyen",
    "venue": "IEEE Access",
    "year": "2026",
    "doi": "10.1109/ACCESS.2026.3656221"
  },
  {
    "title": "Automatic network compression via evolutionary search-guided channel pruning of deep convolutional neural networks",
    "authors": "Kumar, Abhishek, Shibu, Athul, Lee, Dong-Gyu",
    "venue": "Applied Soft Computing",
    "year": "2025",
    "doi": "10.1016/J.ASOC.2025.113521"
  },
  {
    "title": "Deep scene understanding with extended text description for human object interaction detection",
    "authors": "Hye-Seong Hong, Jeong-Cheol Lee, Abhishek Kumar, Sangtae Ahn, Dong-Gyu Lee",
    "venue": "Expert Systems with Applications",
    "year": "2025",
    "doi": "10.1016/j.eswa.2024.125297"
  },
  {
    "title": "Efficient three-stage surrogate-assisted differential evolution for expensive optimization problems",
    "authors": "Abhishek Kumar, Swagatam Das, Václav Snášel",
    "venue": "Swarm and Evolutionary Computation",
    "year": "2025",
    "doi": "10.1016/j.swevo.2025.102093"
  },
  {
    "title": "Enhancing clustering representations with positive proximity and cluster dispersion learning",
    "authors": "Kumar, Abhishek, Lee, Dong-Gyu",
    "venue": "Information Sciences",
    "year": "2025",
    "doi": "10.1016/J.INS.2024.121277"
  },
  {
    "title": "Entropy-weighted medoid shift: An automated clustering algorithm for high-dimensional data",
    "authors": "Kumar, Abhishek, Ajani, Oladayo S., Das, Swagatam, Mallipeddi, Rammohan",
    "venue": "Applied Soft Computing",
    "year": "2025",
    "doi": "10.1016/J.ASOC.2024.112347"
  },
  {
    "title": "An Efficient Differential Grouping Algorithm for Large-Scale Global Optimization",
    "authors": "Kumar, Abhishek, Das, Swagatam, Mallipeddi, Rammohan",
    "venue": "IEEE Transactions on Evolutionary Computation",
    "year": "2024",
    "doi": "10.1109/TEVC.2022.3230070"
  },
  {
    "title": "Covariance matrix adaptation evolution strategy based on correlated evolution paths with application to reinforcement learning",
    "authors": "Ajani, Oladayo S., Kumar, Abhishek, Mallipeddi, Rammohan",
    "venue": "Expert Systems with Applications",
    "year": "2024",
    "doi": "10.1016/J.ESWA.2024.123289"
  },
  {
    "title": "High-density cluster core-based k-means clustering with an unknown number of clusters",
    "authors": "Kumar, Abhimanyu, Kumar, Abhishek, Mallipeddi, Rammohan, Lee, Dong-Gyu",
    "venue": "Applied Soft Computing",
    "year": "2024",
    "doi": "10.1016/J.ASOC.2024.111419"
  },
  {
    "title": "Robust unsupervised domain adaptation by retaining confident entropy via edge concatenation",
    "authors": "Hong, Hye-Seong, Kumar, Abhishek, Lee, Dong-Gyu",
    "venue": "Expert Systems with Applications",
    "year": "2024",
    "doi": "10.1016/J.ESWA.2023.122120"
  },
  {
    "title": "RSSGLT: Remote Sensing Image Segmentation Network Based on Global-Local Transformer",
    "authors": "Kumar, Satyawant, Kumar, Abhishek, Lee, Dong-Gyu",
    "venue": "IEEE Geoscience and Remote Sensing Letters",
    "year": "2024",
    "doi": "10.1109/LGRS.2023.3337879"
  },
  {
    "title": "CMA-ES with exponential based multiplicative covariance matrix adaptation for global optimization",
    "authors": "Karmakar, Bishal, Kumar, Abhishek, Mallipeddi, Rammohan, Lee, Dong-Gyu",
    "venue": "Swarm and Evolutionary Computation",
    "year": "2023",
    "doi": "10.1016/J.SWEVO.2023.101296"
  },
  {
    "title": "Rewarded Meta-Pruning: Meta Learning with Rewards for Channel Pruning",
    "authors": "Shibu, Athul, Kumar, Abhishek, Jung, Heechul, Lee, Dong-Gyu, Yang, Xinsong",
    "venue": "Mathematics",
    "year": "2023",
    "doi": "10.3390/MATH11234849"
  },
  {
    "title": "Self-Adaptive Spherical Search With a Low-Precision Projection Matrix for Real-World Optimization",
    "authors": "Kumar, Abhishek, Das, Swagatam, Kong, Lingping, Snasel, Vaclav",
    "venue": "IEEE Transactions on Cybernetics",
    "year": "2023",
    "doi": "10.1109/TCYB.2021.3119386"
  },
  {
    "title": "Spherical Search based constrained optimization algorithm for power flow analysis of islanded microgrids",
    "authors": "Kumar, Abhishek, Jha, Bablesh Kumar, Das, Swagatam, Mallipeddi, Rammohan",
    "venue": "Applied Soft Computing",
    "year": "2023",
    "doi": "10.1016/J.ASOC.2023.110057"
  },
  {
    "title": "Spherical search with epsilon constraint and gradient-based repair framework for constrained optimization",
    "authors": "Yang, Zhuji, Kumar, Abhishek, Mallipeddi, Rammohan, Lee, Dong-Gyu",
    "venue": "Swarm and Evolutionary Computation",
    "year": "2023",
    "doi": "10.1016/J.SWEVO.2023.101370"
  },
  {
    "title": "Three-Level Hierarchical Management of Active Distribution System With Multimicrogrid",
    "authors": "Singh, Amit, Sethi, Basant Kumar, Kumar, Abhishek, Singh, Devender, Misra, Rakesh Kumar",
    "venue": "IEEE Systems Journal",
    "year": "2023",
    "doi": "10.1109/JSYST.2022.3208032"
  },
  {
    "title": "Trial-based dominance for comparing both the speed and accuracy of stochastic optimizers with standard non-parametric tests",
    "authors": "Price, Kenneth, V, Kumar, Abhishek, Suganthan, P. N.",
    "venue": "Swarm and Evolutionary Computation",
    "year": "2023",
    "doi": "10.1016/J.SWEVO.2023.101287"
  },
  {
    "title": "Adaptive Backward/Forward Sweep for Solving Power Flow of Islanded Microgrids",
    "authors": "Abhimanyu Kumar, Abhishek Kumar, Rammohan Mallipeddi, Dong-Gyu Lee",
    "venue": "Energies",
    "year": "2022",
    "doi": "10.3390/en15249348"
  },
  {
    "title": "Benchmarking Optimization-Based Energy Disaggregation Algorithms",
    "authors": "Oladayo S. Ajani, Abhishek Kumar, Rammohan Mallipeddi, Swagatam Das, Ponnuthurai Nagaratnam Suganthan",
    "venue": "Energies",
    "year": "2022",
    "doi": "10.3390/en15051600"
  },
  {
    "title": "Differential evolution with orthogonal array -based initialization and a novel selection strategy",
    "authors": "Kumar, Abhishek, Biswas, Partha P., Suganthan, Ponnuthurai N.",
    "venue": "Swarm and Evolutionary Computation",
    "year": "2022",
    "doi": "10.1016/J.SWEVO.2021.101010"
  },
  {
    "title": "Improved spherical search with local distribution induced self-adaptation for hard non-convex optimization with and without constraints",
    "authors": "Kumar, Abhishek, Das, Swagatam, Snasel, Vaclav",
    "venue": "Information Sciences",
    "year": "2022",
    "doi": "10.1016/J.INS.2022.09.033"
  },
  {
    "title": "Semantic Segmentation of UAV Images Based on Transformer Framework with Context Information",
    "authors": "Kumar, Satyawant, Kumar, Abhishek, Lee, Dong-Gyu",
    "venue": "Mathematics",
    "year": "2022",
    "doi": "10.3390/MATH10244735"
  },
  {
    "title": "A Benchmark-Suite of real-World constrained multi-objective optimization problems and some baseline results",
    "authors": "Abhishek Kumar, Guohua Wu, Mostafa Z. Ali, Qizhang Luo, Rammohan Mallipeddi, Ponnuthurai Nagaratnam Suganthan, Swagatam Das",
    "venue": "Swarm and Evolutionary Computation",
    "year": "2021",
    "doi": "10.1016/j.swevo.2021.100961"
  },
  {
    "title": "A υ-Constrained Matrix Adaptation Evolution Strategy With Broyden-Based Mutation for Constrained Optimization",
    "authors": "Abhishek Kumar, Swagatam Das, Rakesh Kumar Misra, Devender Singh",
    "venue": "IEEE Transactions on Cybernetics",
    "year": "2021",
    "doi": "10.1109/tcyb.2020.3042853"
  },
  {
    "title": "An Inversion-Free Robust Power-Flow Algorithm for Microgrids",
    "authors": "Abhishek Kumar, Swagatam Das, Rammohan Mallipeddi",
    "venue": "IEEE Transactions on Smart Grid",
    "year": "2021",
    "doi": "10.1109/TSG.2021.3064656"
  },
  {
    "title": "Phase unbalance and PAR constrained optimal active and reactive power scheduling of Virtual Power Plants (VPPs)",
    "authors": "Bablesh Kumar Jha, Amit Singh, Abhishek Kumar, Rakesh Kumar Misra, Devender Singh",
    "venue": "International Journal of Electrical Power & Energy Systems",
    "year": "2021",
    "doi": "10.1016/j.ijepes.2020.106443"
  },
  {
    "title": "Power Flow Analysis of Islanded Microgrids: A Differential Evolution Approach",
    "authors": "Abhishek Kumar, Bablesh Kumar Jha, Swagatam Das, Rammohan Mallipeddi",
    "venue": "IEEE Access",
    "year": "2021",
    "doi": "10.1109/ACCESS.2021.3073509"
  },
  {
    "title": "A modified current injection load flow method under different load model of EV for distribution system",
    "authors": "Bablesh K. Jha, Abhishek Kumar, Dharmendra K. Dheer, Devender Singh, Rakesh K. Misra",
    "venue": "International Transactions on Electrical Energy Systems",
    "year": "2020",
    "doi": "10.1002/2050-7038.12284"
  },
  {
    "title": "A Nested-Iterative Newton-Raphson based Power Flow Formulation for Droop-based Islanded Microgrids",
    "authors": "Abhishek Kumar, Bablesh Kumar Jha, Dharmendra Kumar Dheer, Rakesh Kumar Misra, Devender Singh",
    "venue": "Electric Power Systems Research",
    "year": "2020",
    "doi": "10.1016/j.epsr.2019.106131"
  },
  {
    "title": "A New Current Injection Based Power Flow Formulation",
    "authors": "Abhishek Kumar, Bablesh Kumar Jha, Devender Singh, Rakesh Kumar Misra",
    "venue": "Electric Power Components and Systems",
    "year": "2020",
    "doi": "10.1080/15325008.2020.1758846"
  },
  {
    "title": "A Reference Vector-Based Simplified Covariance Matrix Adaptation Evolution Strategy for Constrained Global Optimization",
    "authors": "Abhishek Kumar, Swagatam Das, Rammohan Mallipeddi",
    "venue": "IEEE Transactions on Cybernetics",
    "year": "2020",
    "doi": "10.1109/tcyb.2020.3013950"
  },
  {
    "title": "A test-suite of non-convex constrained optimization problems from the real-world and some baseline results",
    "authors": "Abhishek Kumar, Guohua Wu, Mostafa Z. Ali, Rammohan Mallipeddi, Ponnuthurai Nagaratnam Suganthan, Swagatam Das",
    "venue": "Swarm and Evolutionary Computation",
    "year": "2020",
    "doi": "10.1016/j.swevo.2020.100693"
  },
  {
    "title": "Day ahead scheduling of PHEVs and D‐BESSs in the presence of DGs in the distribution system",
    "authors": "Bablesh Kumar Jha, Amit Singh, Abhishek Kumar, Dharmendra Kumar Dheer, Devender Singh, Rakesh Kumar Misra",
    "venue": "IET Electrical Systems in Transportation",
    "year": "2020",
    "doi": "10.1049/iet-est.2018.5096"
  },
  {
    "title": "Coordinated effect of PHEVs with DGs on distribution network",
    "authors": "Bablesh Kumar Jha, Abhishek Kumar, Devender Singh, Rakesh Kumar Misra",
    "venue": "International Transactions on Electrical Energy Systems",
    "year": "2019",
    "doi": "10.1002/etep.2800"
  },
  {
    "title": "Current injection‐based Newton–Raphson power‐flow algorithm for droop‐based islanded microgrids",
    "authors": "Abhishek Kumar, Bablesh Kumar Jha, Devender Singh, Rakesh Kumar Misra",
    "venue": "IET Generation, Transmission & Distribution",
    "year": "2019",
    "doi": "10.1049/iet-gtd.2019.0575"
  },
  {
    "title": "Feeder phase balancing using single phase distributed generations considering voltage dependency of loads",
    "authors": "Mishr, S., Kumar, A., Misra, R.K., Singh, D.",
    "venue": "Journal of Advanced Research in Dynamical and Control Systems",
    "year": "2019"
  },
  {
    "title": "Intelligent fuzzy rough set based feature selection using swarm algorithms with improved initialization",
    "authors": "Tarun Maini, Abhishek Kumar, Rakesh Kumar Misra, Devender Singh",
    "venue": "Journal of Intelligent & Fuzzy Systems",
    "year": "2019",
    "doi": "10.3233/JIFS-182606"
  },
  {
    "title": "Nested backward/forward sweep algorithm for power flow analysis of droop regulated islanded microgrids",
    "authors": "Abhishek Kumar, Bablesh Kumar Jha, Dharmendra Kumar Dheer, Devender Singh, Rakesh Kumar Misra",
    "venue": "IET Generation, Transmission & Distribution",
    "year": "2019",
    "doi": "10.1049/iet-gtd.2019.0388"
  },
  {
    "title": "The spherical search algorithm for bound-constrained global optimization problems",
    "authors": "Abhishek Kumar, Rakesh Kumar Misra, Devender Singh, Sujeet Mishra, Swagatam Das",
    "venue": "Applied Soft Computing",
    "year": "2019",
    "doi": "10.1016/j.asoc.2019.105734"
  },
  {
    "title": "Rough Set Based Feature Selection Using Swarm Algorithms with Improved Initialization",
    "authors": "Tarun Maini, Rakesh Kumar Misra, Devender Singh, Abhishek Kumar",
    "venue": "Journal of Computational and Theoretical Nanoscience",
    "year": "2018",
    "doi": "10.1166/jctn.2018.7467"
  }
];

export const conferencePapers: Publication[] = [
  {
    "title": "Modified DipDECK: Deep Clustering Algorithm with Dip-Based K-Means",
    "authors": "Kumar, A., Zdrazil, J., Kong, L.",
    "venue": "Smart Innovation Systems and Technologies",
    "year": "2026",
    "doi": "10.1007/978-3-032-13048-8_25"
  },
  {
    "title": "Scalable Tensor Ranking in Simplifying Multi-criteria Group Decision Making",
    "authors": "Kong, L., Zdražil, J., Kumar, A., Bai, Z., Chu, S.-C.",
    "venue": "Smart Innovation Systems and Technologies",
    "year": "2026",
    "doi": "10.1007/978-3-032-13048-8_7"
  },
  {
    "title": "Encoder-Decoder based Segmentation Model for UAV Street Scene Images",
    "authors": "Kumar, Satyawant, Kumar, Abhishek, Hong, Hye-Seong, Lee, Dong-Gyu",
    "venue": "IEEE International Conference on Consumer Electronics (ICCE)",
    "year": "2023",
    "doi": "10.1109/ICCE56470.2023.10043528"
  },
  {
    "title": "UEQMS: UMAP Embedded Quick Mean Shift Algorithm for High Dimensional Clustering",
    "authors": "Kumar, Abhishek, Das, Swagatam, Mallipeddi, Rammohan",
    "venue": "Proceedings of the AAAI Conference on Artificial Intelligence",
    "year": "2023"
  },
  {
    "title": "CSS-A Cheap-Surrogate-Based Selection Operator for Multi-objective Optimization",
    "authors": "Kong, Lingping, Kumar, Abhishek, Snasel, Vaclav, Das, Swagatam, Kromer, Pavel, Ojha, Varun",
    "venue": "Lecture Notes in Computer Science",
    "year": "2022",
    "doi": "10.1007/978-3-031-21094-5_5"
  },
  {
    "title": "GridShift: A Faster Mode-seeking Algorithm for Image Segmentation and Object Tracking",
    "authors": "Kumar, Abhishek, Ajani, Oladayo S., Das, Swagatam, Mallipeddi, Rammohan",
    "venue": "IEEE Conference on Computer Vision and Pattern Recognition",
    "year": "2022",
    "doi": "10.1109/CVPR52688.2022.00796"
  },
  {
    "title": "A modified covariance matrix adaptation evolution strategy for real-world constrained optimization problems",
    "authors": "Abhishek Kumar, Swagatam Das, Ivan Zelinka",
    "venue": "Proceedings of the 2020 Genetic and Evolutionary Computation Conference Companion",
    "year": "2020",
    "doi": "10.1145/3377929.3398185"
  },
  {
    "title": "Testing A Multi-Operator based Differential Evolution Algorithm on the 100-Digit Challenge for Single Objective Numerical Optimization",
    "authors": "Abhishek Kumar, Rakesh Kumar Misra, Devender Singh, Swagatam Das",
    "venue": "2019 IEEE Congress on Evolutionary Computation (CEC)",
    "year": "2019",
    "doi": "10.1109/cec.2019.8789907"
  },
  {
    "title": "Feature selection with intelligent dynamic swarm and fuzzy rough set",
    "authors": "Tarun Maini, Abhishek Kumar, Rakesh Kumar Misra, Devender Singh",
    "venue": "2017 International Conference on Computing, Communication and Automation (ICCCA)",
    "year": "2017",
    "doi": "10.1109/ccaa.2017.8229831"
  },
  {
    "title": "Improving the local search capability of Effective Butterfly Optimizer using Covariance Matrix Adapted Retreat Phase",
    "authors": "Abhishek Kumar, Rakesh Kumar Misra, Devender Singh",
    "venue": "2017 IEEE Congress on Evolutionary Computation (CEC)",
    "year": "2017",
    "doi": "10.1109/cec.2017.7969524"
  },
  {
    "title": "Rough set based feature selection using swarm intelligence with distributed sampled initialisation",
    "authors": "Tarun Maini, Abhishek Kumar, RakeshKumar Misra, Devender Singh",
    "venue": "2017 6th International Conference on Computer Applications In Electrical Engineering-Recent Advances (CERA)",
    "year": "2017",
    "doi": "10.1109/cera.2017.8343307"
  },
  {
    "title": "Butterfly optimizer",
    "authors": "Abhishek Kumar, Rakesh Kumar Misra, Devender Singh",
    "venue": "2015 IEEE Workshop on Computational Intelligence: Theories, Applications and Future Directions (WCI)",
    "year": "2015",
    "doi": "10.1109/wci.2015.7495523"
  }
];

export const bookChapters: Publication[] = [
  {
    "title": "Spherical Search Algorithm: A Metaheuristic for Bound-Constrained Optimization",
    "authors": "Rakesh Kumar Misra, Devender Singh, Abhishek Kumar",
    "venue": "Optimization, Variational Analysis and Applications",
    "year": "2021",
    "doi": "10.1007/978-981-16-1819-2_19"
  },
  {
    "title": "Butterfly Constrained Optimizer for Constrained Optimization Problems",
    "authors": "Abhishek Kumar, Tarun Maini, Rakesh Kumar Misra, Devender Singh",
    "venue": "Advances in Intelligent Systems and Computing",
    "year": "2019",
    "doi": "10.1007/978-981-13-1135-2_36"
  },
  {
    "title": "Butterfly Optimizer for Placement and Sizing of Distributed Generation for Feeder Phase Balancing",
    "authors": "Sujeet Mishra, Abhishek Kumar, Devender Singh, Rakesh Kumar Misra",
    "venue": "Advances in Intelligent Systems and Computing",
    "year": "2019",
    "doi": "10.1007/978-981-13-1135-2_39"
  },
  {
    "title": "Fuzzy Rough Set-Based Feature Selection with Improved Seed Population in PSO and IDS",
    "authors": "Tarun Maini, Abhishek Kumar, Rakesh Kumar Misra, Devender Singh",
    "venue": "Advances in Intelligent Systems and Computing",
    "year": "2019",
    "doi": "10.1007/978-981-13-1135-2_11"
  }
];
